[package]
name = "gff_diff"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
bio = "*"
serde_json = "*"
multimap = "*"
getopts = "*"
regex = "*"
rayon = "*"
ignore-result = "*"

[profile.dev]
opt-level = 3