[package]
name = "gff_diff"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
bio = "*"
#json = "*"
serde_json = "*"
multimap = "0.4.0"
getopts = "0.2.18"
regex = "1.1.2"

[profile.dev]
opt-level = 3