[package]
name = "gff_diff"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
bio = "*"
#json = "*"
serde_json = "*"
multimap = "*"
getopts = "*"
regex = "*"

[profile.dev]
opt-level = 3